### ISSUE TITLE
The solution build of libSkiaSharp's Debug|x64 solution fails.

### ISSUE THREAD

**Issue by pragmatrix** [pragmatrix/BuildOnSave#46]
VS 2015
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BuildOnSave.BackgroundBuild2.<>c__DisplayClass30_0.<projectInstancesOfPaths>b__1(String path)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BuildOnSave.BackgroundBuild2.projectInstancesOfPaths(ProjectInstance[] allInstances, IEnumerable`1 paths)
   at BuildOnSave.BackgroundBuild2.tryMakeBuildRequest(String startupProject_, String[] changedProjectPaths)
   at BuildOnSave.Driver.beginBuild(String startupProject_, String[] changedProjects)
   at BuildOnSave.Driver.beginBuild(Solution solution, BuildType buildType, IEnumerable`1 projects)
   at BuildOnSave.Driver.beginBuild()---------- BuildOnSave CRASHED, please report to https://www.github.com/pragmatrix/BuildOnSave/issues
```

**Comment by RyanHerbert** [comment]
I'm getting a crash on a brand new ASP.NET Core 2.0 application with this same stack trace.

I'd also like to say thanks for this extension, its a huge time saver and one of the first things I recommend when people install Visual Studio.

**Comment by pragmatrix** [comment]
Thank you @RyanHerbert.

I've put a few hours into this today and built [a new release] that supports .NET Core and CPP (and perhaps other project types). It fixes the original issue with the libSkiaSharp project, and seems to work with well with .NET Core projects.

I am closing this issue now, but feel free to report back with any problems you find.

[a new release]: https://github.com/pragmatrix/BuildOnSave/releases/tag/0.29b

**Comment by RyanHerbert** [comment]
Awesome, just grabbed the new version and it looks like its working great.
