### ISSUE TITLE
NullReferenceException in Xamarin solution VS2017 15.8 Preview 1

### ISSUE THREAD

**Issue by leonmeijer** [pragmatrix/BuildOnSave#51]
BuildOnSave is not working. As soon as I save, the Output Window shows:

System.NullReferenceException: Object reference not set to an instance of an object.
   at BuildOnSave.Projects.DependentProjectKeys(BuildDependencies dependencies, Project project)
   at BuildOnSave.Projects.DependentMap(BuildDependencies dependencies, Project[] all)
   at BuildOnSave.Projects.AffectedProjects(BuildDependencies dependencies, Project[] all, Project[] roots)
   at BuildOnSave.BackgroundBuild2.tryMakeBuildRequest(String startupProject_, String[] changedProjectPaths)
   at BuildOnSave.Driver.beginBuild(String startupProject_, String[] changedProjects)
   at BuildOnSave.Driver.beginBuild(Solution solution, BuildType buildType, IEnumerable`1 projects)
   at BuildOnSave.Driver.beginBuild()

Another solution with just a Windows Forms project works fine in v15.8

**Comment by pragmatrix** [comment]
Was the project compiling with VS 15.7?

**Comment by leonmeijer** [comment]
Yes, the project is compiling fine.

**Comment by pragmatrix** [comment]
I've created some Xamarin Android projects today with VS15.8 Preview 5 and could not reproduce the exception above. If the problem persists, please reopen this ticket and provide a Xamarin project that shows the problem.
